kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 8et67/olw/K5OfV+oizz5hm1YdOijXPohKrM7MmnMaQ=
      - identity: {}
